// Code generated by goctl. DO NOT EDIT.
package types

type WriteRequest struct {
	Did       int   `path:"did"`
	Timestamp int64 `path:"timestamp"`
}

type WriteResponse struct {
	Message string `json:"message"`
	Code    int    `json:"code"`
}

type ReadRequest struct {
	Did   int   `path:"did"`
	Start int64 `path:"start"`
	End   int64 `path:"end"`
}

type ReadResponse struct {
	Timestamp []int64  `path:"timestamp"`
	Data      []string `path:"data"`
}
